### ISSUE TITLE
A consult for my project

### ISSUE THREAD

**Issue by Jarilloj2209** [dhruvnagarajan/Perceptron-Passive-DDoS-Detection#3]
Hi my name is Chucho, 
I am writing because I would like to use your code to make a real time classifier,  indeed I am figuring out a way to understand how you had normalized the IP adress in the text "test_data_udp". Also, it will be very kind of you if you can explain me how the files "IPtrain_label_udp.txt" and "test_label_udp.txt" work.

**Comment by dhruvnagarajan** [comment]
#1

**Comment by dhruvnagarajan** [comment]
IPtrain_... files have been renamed to be self-explanatory now.

test_label_udp.txt has also been renamed.
It contains labels for every tuple passed to `input tensors`. It is one-hot encoded.
0 represents that the `input` passed is not an attack packet.
1 represents that the `input` passed is an attack packet.
